In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv("Customer Purchasing Behaviors.csv")
df

,user_id,age,annual_income,purchase_amount,loyalty_score,region,purchase_frequency
0,1,25,45000,200,4.5,North,12
1,2,34,55000,350,7.0,South,18
2,3,45,65000,500,8.0,West,22
3,4,22,30000,150,3.0,East,10
4,5,29,47000,220,4.8,North,13
...,...,...,...,...,...,...,...
233,234,40,60000,450,7.2,West,20
234,235,38,59000,430,6.9,North,20
235,236,54,74000,630,9.4,South,27
236,237,32,52000,360,5.8,West,18
237,238,31,51000,340,5.6,North,17

In [2]:
df.describe()

,user_id,age,annual_income,purchase_amount,loyalty_score,purchase_frequency
count,238.000000,238.000000,238.000000,238.000000,238.000000,238.000000
mean,119.500000,38.676471,57407.563025,425.630252,6.794118,19.798319
std,68.848868,9.351118,11403.875717,140.052062,1.899047,4.562884
min,1.000000,22.000000,30000.000000,150.000000,3.000000,10.000000
25%,60.250000,31.000000,50000.000000,320.000000,5.500000,17.000000
50%,119.500000,39.000000,59000.000000,440.000000,7.000000,20.000000
75%,178.750000,46.750000,66750.000000,527.500000,8.275000,23.000000
max,238.000000,55.000000,75000.000000,640.000000,9.500000,28.000000

In [3]:
## Data Cleaning

In [4]:
df.isnull().sum() # No missing values in dataset

user_id               0
age                   0
annual_income         0
purchase_amount       0
loyalty_score         0
region                0
purchase_frequency    0
dtype: int64

In [5]:
df.duplicated().sum() # No duplicate values in dataset

np.int64(0)

In [6]:
age=df["age"] #No unrealistic age values in dataset
print("Maximum Age :",age.max())
print("Minimum Age :",age.min())

Maximum Age : 55
Minimum Age : 22

In [7]:
score=df["loyalty_score"] #No unrealistic loyalty score in dataset
print("Min Loyalty Score :",score.min())
print("Max loyalty Score :",score.max())

Min Loyalty Score : 3.0
Max loyalty Score : 9.5

In [8]:
df.dtypes

user_id                 int64
age                     int64
annual_income           int64
purchase_amount         int64
loyalty_score         float64
region                    str
purchase_frequency      int64
dtype: object

In [9]:
am=df["purchase_amount"] 
an=df["annual_income"]
print("Min purchase amount :",am.max())
print("Max purchase amount :",am.min())
print("max Annual Income :",an.max())
print("Min Annual Income :",an.min())

Min purchase amount : 640
Max purchase amount : 150
max Annual Income : 75000
Min Annual Income : 30000

In [10]:
## Groupby And Aggregation

In [11]:
df.groupby("region").purchase_amount.agg(["mean"]) # avg purchase amounts in each regions

              mean
region
East    320.000000
North   358.589744
South   416.883117
West    510.519481

In [12]:
df.groupby("region").user_id.agg(["count"]) # Count the number of customers in each region.

        count
region
East        6
North      78
South      77
West       77

In [13]:
df.groupby("region").purchase_frequency.agg(["max","mean"]) # the highest average purchase frequency region

        max       mean
region
East     22  16.666667
North    25  17.653846
South    28  19.467532
West     28  22.545455

In [14]:
df.groupby("region").annual_income.agg(["min","max"])  # the maximum and minimum annual income for each region

          min    max
region
East    30000  60000
North   31000  70000
South   32000  75000
West    32000  75000

In [15]:
score=df["loyalty_score"] # Divide customers into three loyalty categories and count customers in each category
low=0 # 0-4
medium=0 # 4-7
high=0 # 7-10
for i in score:
    if i>=0 and i<4:
        low=low+1
    elif i>=4 and i<7:
        medium=medium+1
    elif i>=7 and i<=10:
        high=high+1
print("Low Loyalty Score customers :",low)
print("Medium Loyalty Score customers :",medium)
print("High Loyalty Score customers :",high)

Low Loyalty Score customers : 16
Medium Loyalty Score customers : 100
High Loyalty Score customers : 122

In [16]:
df.groupby("age").purchase_amount.agg(["sum"]) # the total purchase amount for each age group.

      sum
age
22    150
23    160
24   2380
25    400
26   1920
27   1840
28   2000
29   2340
30   2400
31   3020
32   2880
33   5320
34    700
35    390
36   3200
37   3360
38   3440
39   3520
40   3600
41   6720
42   3640
43   3290
44    460
45   4000
46   4080
47    530
48   3850
49   4720
50   8400
51   4200
52   4880
53    620
54   4410
55   4480

In [17]:
df.groupby("region").loyalty_score.agg(["mean"]) # region has the highest average loyalty score - West

            mean
region
East    5.400000
North   5.865385
South   6.725974
West    7.911688

In [18]:
income=df["annual_income"]
lowincome=[]
highincome=[]
for i in income:
    if i<50000:
        lowincome.append(i)
    elif i>=50000:
        highincome.append(i)
print(np.mean(lowincome))
print(np.mean(highincome))

41915.254237288136
62513.96648044693

In [19]:
## Sorting & Filtering

In [20]:
df.sort_values("purchase_amount", ascending=False).head(10) # top 10 customers with the highest purchase amount.

,user_id,age,annual_income,purchase_amount,loyalty_score,region,purchase_frequency
34,35,55,75000,640,9.5,South,28
59,60,55,75000,640,9.5,West,28
89,90,55,75000,640,9.5,West,28
209,210,55,75000,640,9.5,West,28
149,150,55,75000,640,9.5,West,28
119,120,55,75000,640,9.5,West,28
179,180,55,75000,640,9.5,West,28
145,146,54,74000,630,9.4,South,27
205,206,54,74000,630,9.4,South,27
175,176,54,74000,630,9.4,South,27

In [21]:
x=df[df["region"]=="West"] #only those customers from the West region whose loyalty score is greater than 8.
x[x["loyalty_score"]>8]

,user_id,age,annual_income,purchase_amount,loyalty_score,region,purchase_frequency
14,15,49,69000,590,8.9,West,24
25,26,47,67000,530,8.3,West,23
28,29,51,71000,600,9.0,West,25
38,39,53,73000,620,9.3,West,27
44,45,52,72000,610,9.2,West,26
47,48,50,70000,600,9.0,West,25
50,51,49,69000,590,8.9,West,24
59,60,55,75000,640,9.5,West,28
62,63,51,71000,600,9.0,West,25
68,69,48,68000,550,8.5,West,24
74,75,52,72000,610,9.2,West,26
77,78,50,70000,600,9.0,West,25
80,81,49,69000,590,8.9,West,24
89,90,55,75000,640,9.5,West,28
92,93,51,71000,600,9.0,West,25
98,99,48,68000,550,8.5,West,24
104,105,52,72000,610,9.2,West,26
107,108,50,70000,600,9.0,West,25
110,111,49,69000,590,8.9,West,24
119,120,55,75000,640,9.5,West,28
122,123,51,71000,600,9.0,West,25
128,129,48,68000,550,8.5,West,24
134,135,52,72000,610,9.2,West,26
137,138,50,70000,600,9.0,West,25
140,141,49,69000,590,8.9,West,24
149,150,55,75000,640,9.5,West,28
152,153,51,71000,600,9.0,West,25
158,159,48,68000,550,8.5,West,24
164,165,52,72000,610,9.2,West,26
167,168,50,70000,600,9.0,West,25
170,171,49,69000,590,8.9,West,24
179,180,55,75000,640,9.5,West,28
182,183,51,71000,600,9.0,West,25
188,189,48,68000,550,8.5,West,24
194,195,52,72000,610,9.2,West,26
197,198,50,70000,600,9.0,West,25
200,201,49,69000,590,8.9,West,24
209,210,55,75000,640,9.5,West,28
212,213,51,71000,600,9.0,West,25
218,219,48,68000,550,8.5,West,24
224,225,52,72000,610,9.2,West,26
227,228,50,70000,600,9.0,West,25
230,231,49,69000,590,8.9,West,24

In [22]:
df[(df["age"]>=30) & (df["age"]<=40)]["purchase_frequency"].mean() # the average purchase frequency for customers in the 30–40 age group

np.float64(18.71951219512195)

In [23]:
e=df[df["region"]=="East"]["purchase_amount"].idxmax() # the customer with the highest purchase amount in each region
w=df[df["region"]=="West"]["purchase_amount"].idxmax()
n=df[df["region"]=="North"]["purchase_amount"].idxmax()
s=df[df["region"]=="South"]["purchase_amount"].idxmax()

In [24]:
df.loc[e]

user_id                  30
age                      40
annual_income         60000
purchase_amount         450
loyalty_score           7.2
region                 East
purchase_frequency       22
Name: 29, dtype: object

In [25]:
df.loc[w]

user_id                  60
age                      55
annual_income         75000
purchase_amount         640
loyalty_score           9.5
region                 West
purchase_frequency       28
Name: 59, dtype: object

In [26]:
df.loc[n]

user_id                   9
age                      50
annual_income         70000
purchase_amount         600
loyalty_score           9.0
region                North
purchase_frequency       25
Name: 8, dtype: object

In [27]:
df.loc[s]

user_id                  35
age                      55
annual_income         75000
purchase_amount         640
loyalty_score           9.5
region                South
purchase_frequency       28
Name: 34, dtype: object