In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("Virat-Kohli-International-Cricket-Centuries.csv")

In [3]:
df

,No.,Runs,Against,Position,Innings,Venue,Ground,Date,Result
0,1,107,Sri Lanka,4,2,"Eden Gardens, Kolkata",Home,24-Dec-09,Won
1,2,102*,Bangladesh,3,2,"Sher-e-Bangla Cricket Stadium, Dhaka",Away,11-Jan-10,Won
2,3,118,Australia,3,2,"APCA-VDCA Stadium, Visakhapatnam",Home,20-Oct-10,Won
3,4,105,New Zealand,3,1,"Nehru Stadium, Guwahati",Home,28-Nov-10,Won
4,5,100*,Bangladesh,4,1,"Sher-e-Bangla Cricket Stadium, Dhaka",Away,19-Feb-11,Won
...,...,...,...,...,...,...,...,...,...
75,76,121,West Indies,4,1,"Queen's Park Oval, Port of Spain",Away,20-Jul-23,Drawn
76,77,122*,Pakistan,3,1,"R. Premadasa Stadium, Colombo",Neutral,11-Sep-23,Won
77,78,103*,Bangladesh,3,2,"Maharashtra Cricket Association Stadium, Pune",Home,19-Oct-23,Won
78,79,101*,South Africa,3,1,"Eden Gardens, Kolkata",NaN,05-Nov,Won
79,80,117,New Zealand,3,1,"Wankhede Stadium, Mumbai",Home,15-Nov-23,Won

In [4]:
# Q1. How many centuries has Virat Kohli scored against each opponent team? Which team has the highest number of centuries scored against them?
# Q2. Analyze centuries across Home, Away, and Neutral grounds — what is the total century count and average runs scored at each location?
# Q3. In matches where Kohli scored a century — compare his average runs in matches that were Won vs Lost. Did winning teams score more?
# Q4. Which batting position (from the Position column) has the most centuries? At what position does Kohli perform best?
# Q5. Compare Kohli's average runs in centuries scored during the 1st innings vs the 2nd innings — which innings sees better performance?
# Q6. Using a combination of Ground type (Home/Away) and Match Result — where did Kohli score more runs: Home wins or Away wins?
# Q7. What is Kohli's average runs against each opponent team (only in century matches)? Which team has faced his highest average score?
# Q8. Apply a grouped analysis on Innings and Ground combination together — find the total century count and average runs for each combination.

In [5]:
df.groupby(by=["Against"]).Runs.agg(["count"]) #Que1

               count
Against
 Afghanistan       1
 Australia        16
 Bangladesh        6
 England           8
 New Zealand       8
 Pakistan          2
 South Africa      7
 Sri Lanka        15
 West Indies      11
 Zimbabwe          1
Bangladesh         1
New Zealand        1
Pakistan           1
South Africa       1
West Indies        1

In [6]:
df["Runs"] = df["Runs"].str.replace("*", "", regex=False) #Que2
df["Runs"] = pd.to_numeric(df["Runs"], errors='coerce')
df.groupby("Ground")["Runs"].agg(["count", "mean"]).round(2)

         count    mean
Ground
Away        36  122.58
Home        37  141.49
Neutral      6  129.17

In [7]:
df.groupby("Result").Runs.mean() #Que3

Result
Drawn         144.111111
Lost          122.846154
Lost (D/L)    107.000000
Tied          157.000000
Won           132.072727
Won (D/L)     102.000000
Name: Runs, dtype: float64

In [8]:
df[df["Runs"]>100]

,No.,Runs,Against,Position,Innings,Venue,Ground,Date,Result
0,1,107,Sri Lanka,4,2,"Eden Gardens, Kolkata",Home,24-Dec-09,Won
1,2,102,Bangladesh,3,2,"Sher-e-Bangla Cricket Stadium, Dhaka",Away,11-Jan-10,Won
2,3,118,Australia,3,2,"APCA-VDCA Stadium, Visakhapatnam",Home,20-Oct-10,Won
3,4,105,New Zealand,3,1,"Nehru Stadium, Guwahati",Home,28-Nov-10,Won
5,6,107,England,4,1,"Sophia Gardens, Cardiff",Away,16-Sep-11,Lost (D/L)
...,...,...,...,...,...,...,...,...,...
75,76,121,West Indies,4,1,"Queen's Park Oval, Port of Spain",Away,20-Jul-23,Drawn
76,77,122,Pakistan,3,1,"R. Premadasa Stadium, Colombo",Neutral,11-Sep-23,Won
77,78,103,Bangladesh,3,2,"Maharashtra Cricket Association Stadium, Pune",Home,19-Oct-23,Won
78,79,101,South Africa,3,1,"Eden Gardens, Kolkata",NaN,05-Nov,Won
79,80,117,New Zealand,3,1,"Wankhede Stadium, Mumbai",Home,15-Nov-23,Won

In [9]:
df.describe()

           No.        Runs   Position   Innings
count  80.0000   80.000000  80.000000  80.00000
mean   40.5000  131.550000   3.500000   1.67500
std    23.2379   35.094772   0.656033   0.67082
min     1.0000  100.000000   2.000000   1.00000
25%    20.7500  107.000000   3.000000   1.00000
50%    40.5000  118.500000   3.000000   2.00000
75%    60.2500  139.250000   4.000000   2.00000
max    80.0000  254.000000   6.000000   4.00000

In [10]:
df.groupby("Position").Runs.count() #Que 4 = Maximum centuries in 3rd postion

Position
2     1
3    43
4    32
5     3
6     1
Name: Runs, dtype: int64

In [11]:
df

,No.,Runs,Against,Position,Innings,Venue,Ground,Date,Result
0,1,107,Sri Lanka,4,2,"Eden Gardens, Kolkata",Home,24-Dec-09,Won
1,2,102,Bangladesh,3,2,"Sher-e-Bangla Cricket Stadium, Dhaka",Away,11-Jan-10,Won
2,3,118,Australia,3,2,"APCA-VDCA Stadium, Visakhapatnam",Home,20-Oct-10,Won
3,4,105,New Zealand,3,1,"Nehru Stadium, Guwahati",Home,28-Nov-10,Won
4,5,100,Bangladesh,4,1,"Sher-e-Bangla Cricket Stadium, Dhaka",Away,19-Feb-11,Won
...,...,...,...,...,...,...,...,...,...
75,76,121,West Indies,4,1,"Queen's Park Oval, Port of Spain",Away,20-Jul-23,Drawn
76,77,122,Pakistan,3,1,"R. Premadasa Stadium, Colombo",Neutral,11-Sep-23,Won
77,78,103,Bangladesh,3,2,"Maharashtra Cricket Association Stadium, Pune",Home,19-Oct-23,Won
78,79,101,South Africa,3,1,"Eden Gardens, Kolkata",NaN,05-Nov,Won
79,80,117,New Zealand,3,1,"Wankhede Stadium, Mumbai",Home,15-Nov-23,Won

In [12]:
df.groupby(by=["Innings"]).Runs.mean().head(2) #Que5

Innings
1    137.787879
2    129.071429
Name: Runs, dtype: float64

In [13]:
df.groupby(["Ground","Result"]).Runs.mean() #Que6

Ground   Result
Away     Drawn         132.200000
         Lost          124.600000
         Lost (D/L)    107.000000
         Won           120.894737
         Won (D/L)     102.000000
Home     Drawn         159.000000
         Lost          117.000000
         Tied          157.000000
         Won           141.068966
Neutral  Won           129.166667
Name: Runs, dtype: float64

In [14]:
df.groupby("Against").Runs.mean().sort_values(ascending=False) #Que7

Against
 South Africa    152.142857
 Pakistan        145.000000
 England         137.250000
 Sri Lanka       133.800000
 Bangladesh      131.833333
 West Indies     130.363636
 New Zealand     129.375000
 Australia       125.187500
 Afghanistan     122.000000
Pakistan         122.000000
West Indies      121.000000
New Zealand      117.000000
 Zimbabwe        115.000000
Bangladesh       103.000000
South Africa     101.000000
Name: Runs, dtype: float64

In [15]:
df

,No.,Runs,Against,Position,Innings,Venue,Ground,Date,Result
0,1,107,Sri Lanka,4,2,"Eden Gardens, Kolkata",Home,24-Dec-09,Won
1,2,102,Bangladesh,3,2,"Sher-e-Bangla Cricket Stadium, Dhaka",Away,11-Jan-10,Won
2,3,118,Australia,3,2,"APCA-VDCA Stadium, Visakhapatnam",Home,20-Oct-10,Won
3,4,105,New Zealand,3,1,"Nehru Stadium, Guwahati",Home,28-Nov-10,Won
4,5,100,Bangladesh,4,1,"Sher-e-Bangla Cricket Stadium, Dhaka",Away,19-Feb-11,Won
...,...,...,...,...,...,...,...,...,...
75,76,121,West Indies,4,1,"Queen's Park Oval, Port of Spain",Away,20-Jul-23,Drawn
76,77,122,Pakistan,3,1,"R. Premadasa Stadium, Colombo",Neutral,11-Sep-23,Won
77,78,103,Bangladesh,3,2,"Maharashtra Cricket Association Stadium, Pune",Home,19-Oct-23,Won
78,79,101,South Africa,3,1,"Eden Gardens, Kolkata",NaN,05-Nov,Won
79,80,117,New Zealand,3,1,"Wankhede Stadium, Mumbai",Home,15-Nov-23,Won

In [16]:
df.groupby(["Innings","Ground"]).Runs.agg(["count","mean"]) #Que8

                 count        mean
Innings Ground
1       Away        12  124.666667
        Home        16  155.687500
        Neutral      4  114.750000
2       Away        20  123.250000
        Home        20  132.000000
        Neutral      2  158.000000
3       Away         2  103.000000
        Home         1  104.000000
4       Away         2  123.000000