In [1]:
import pandas as pd
df=pd.read_csv("ufo.csv")

In [2]:
df

,City,Colors Reported,Shape Reported,State,Time
0,Ithaca,NaN,TRIANGLE,NY,6/1/1930 22:00
1,Willingboro,NaN,OTHER,NJ,6/30/1930 20:00
2,Holyoke,NaN,OVAL,CO,2/15/1931 14:00
3,Abilene,NaN,DISK,KS,6/1/1931 13:00
4,New York Worlds Fair,NaN,LIGHT,NY,4/18/1933 19:00
...,...,...,...,...,...
18236,Grant Park,NaN,TRIANGLE,IL,12/31/2000 23:00
18237,Spirit Lake,NaN,DISK,IA,12/31/2000 23:00
18238,Eagle River,NaN,NaN,WI,12/31/2000 23:45
18239,Eagle River,RED,LIGHT,WI,12/31/2000 23:45
18240,Ybor,NaN,OVAL,FL,12/31/2000 23:59

In [3]:
df.groupby("Shape Reported").State.agg(["count"]) # Count UFO Reoports By Shape

                count
Shape Reported
CHEVRON           248
CIGAR             617
CIRCLE           1365
CONE               60
CRESCENT            2
CROSS              36
CYLINDER          294
DELTA               7
DIAMOND           234
DISK             2122
DOME                1
EGG               197
FIREBALL         1039
FLARE               1
FLASH             188
FORMATION         434
HEXAGON             1
LIGHT            2803
OTHER            1402
OVAL              845
PYRAMID             1
RECTANGLE         303
ROUND               2
SPHERE           1054
TEARDROP          119
TRIANGLE         1889
VARIOUS           333

In [4]:
df.groupby(["Colors Reported"]).City.agg(["count"]) # Ufo Sighting count By colour

                        count
Colors Reported
BLUE                      449
GREEN                     530
GREEN BLUE                 34
ORANGE                    528
ORANGE BLUE                10
ORANGE GREEN               23
ORANGE GREEN BLUE           5
ORANGE YELLOW              26
ORANGE YELLOW BLUE          1
ORANGE YELLOW GREEN         1
RED                       778
RED BLUE                   78
RED GREEN                  89
RED GREEN BLUE             33
RED ORANGE                 44
RED ORANGE BLUE             3
RED ORANGE GREEN            3
RED ORANGE YELLOW           4
RED ORANGE YELLOW BLUE      1
RED YELLOW                 25
RED YELLOW BLUE             3
RED YELLOW GREEN            9
RED YELLOW GREEN BLUE       4
YELLOW                    168
YELLOW BLUE                 6
YELLOW GREEN               17
YELLOW GREEN BLUE           5

In [5]:
df.groupby(["State","Shape Reported"]).Time.agg(["count"]) # Combination Of State And Shape

                      count
State Shape Reported
AK    CIGAR               6
      CIRCLE              8
      CONE                1
      CYLINDER            2
      DIAMOND             1
...                     ...
WY    OVAL                1
      SPHERE              4
      TEARDROP            1
      TRIANGLE            5
      VARIOUS             1

[896 rows x 1 columns]

In [6]:
df.groupby('Shape Reported')['State'].nunique() # Shapes in Diffrent States

Shape Reported
CHEVRON      43
CIGAR        48
CIRCLE       50
CONE         26
CRESCENT      2
CROSS        14
CYLINDER     45
DELTA         6
DIAMOND      42
DISK         50
DOME          1
EGG          44
FIREBALL     50
FLARE         1
FLASH        40
FORMATION    48
HEXAGON       1
LIGHT        50
OTHER        50
OVAL         50
PYRAMID       1
RECTANGLE    46
ROUND         2
SPHERE       50
TEARDROP     40
TRIANGLE     50
VARIOUS      46
Name: State, dtype: int64

In [7]:
df.describe()

           City Colors Reported Shape Reported  State              Time
count     18215            2882          15597  18241             18241
unique     6475              27             27     52             16145
top     Seattle             RED          LIGHT     CA  11/16/1999 19:00
freq        187             780           2803   2529                27

In [8]:
df.groupby("State")["Shape Reported"].nunique()

State
AK    16
AL    16
AR    18
AZ    20
CA    22
CO    17
CT    17
Ca     1
DE    11
FL    19
Fl     0
GA    20
HI    17
IA    19
ID    16
IL    19
IN    20
KS    19
KY    18
LA    17
MA    17
MD    16
ME    17
MI    19
MN    19
MO    20
MS    17
MT    16
NC    20
ND    13
NE    16
NH    18
NJ    18
NM    19
NV    19
NY    19
OH    20
OK    17
OR    20
PA    23
RI    13
SC    18
SD    13
TN    19
TX    21
UT    17
VA    20
VT    15
WA    21
WI    21
WV    16
WY    17
Name: Shape Reported, dtype: int64

In [9]:
df.groupby(["Colors Reported","Shape Reported"]).City.agg(["count"])

                                  count
Colors Reported   Shape Reported
BLUE              CHEVRON             5
                  CIGAR               9
                  CIRCLE             29
                  CONE                1
                  CYLINDER            7
...                                 ...
YELLOW GREEN      OTHER               2
                  SPHERE              1
                  TEARDROP            1
YELLOW GREEN BLUE CYLINDER            1
                  OTHER               2

[234 rows x 1 columns]

In [10]:
df.groupby("State")["Colors Reported"].nunique() # Har State Mein Kitne Alag-Alag Colors Report Kiye Gaye

State
AK     7
AL     6
AR     8
AZ    13
CA    20
CO    11
CT     7
Ca     0
DE     4
FL    14
Fl     1
GA    13
HI     7
IA     9
ID     5
IL    14
IN    11
KS     8
KY     8
LA     7
MA     9
MD    11
ME     8
MI    13
MN     8
MO    11
MS     6
MT     6
NC    13
ND     3
NE     5
NH    11
NJ     8
NM     6
NV     8
NY    12
OH    13
OK     9
OR    13
PA    14
RI     4
SC     8
SD     7
TN    10
TX    15
UT     8
VA    11
VT     4
WA    16
WI    10
WV     7
WY     5
Name: Colors Reported, dtype: int64